name: Versioning and Documentation
on:
  push:
    branches: [ "dev" ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  pull_request_target:
    types:
      - closed 
    branches: [ "dev" ]
  workflow_dispatch:
env:
  PROJECT: verkadaModule
jobs:
  Patch:
    if: github.event_name == 'push' && !(startsWith(github.event.head_commit.message, 'Merge'))
    outputs:
      version: ${{ steps.buildUpdate.outputs.v }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - name: Run module maintenance script
        id: buildUpdate
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module platyPS
          $loc = Get-Location
          $Env:PSModulePath = $Env:PSModulePath+":$loc"
          Import-Module -name $env:PROJECT
          $output = (./maintenance/updateMod.ps1)
          echo "v=$output" >> $env:GITHUB_OUTPUT
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Bumping release to ${{ steps.buildUpdate.outputs.v }}
  Minor:
    if: startsWith(github.head_ref, 'minor/') && github.event.pull_request.merged == true
    outputs:
      version: ${{ steps.buildUpdate.outputs.v }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - name: Run module maintenance script
        id: buildUpdate
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module platyPS
          $loc = Get-Location
          $Env:PSModulePath = $Env:PSModulePath+":$loc"
          Import-Module -name $env:PROJECT
          $output = (./maintenance/updateMod.ps1 minor)
          echo "v=$output" >> $env:GITHUB_OUTPUT
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Bumping release to ${{ steps.buildUpdate.outputs.v }}
          branch: dev
  Major:
    if: startsWith(github.head_ref, 'major/') && github.event.pull_request.merged == true
    outputs:
      version: ${{ steps.buildUpdate.outputs.v }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - name: Run module maintenance script
        id: buildUpdate
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module platyPS
          $loc = Get-Location
          $Env:PSModulePath = $Env:PSModulePath+":$loc"
          Import-Module -name $env:PROJECT
          $output = (./maintenance/updateMod.ps1 major)
          echo "v=$output" >> $env:GITHUB_OUTPUT
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Bumping release to ${{ steps.buildUpdate.outputs.v }}
          branch: dev